---
# - include_tasks: setup-RedHat.yml
  # when: ansible_os_family == 'RedHat'

# - include_tasks: setup-Debian.yml
  # when: ansible_os_family == 'Debian'

- name: uninstall Elasticsearch
  become: yes
  yum:
    name: elasticsearch
    state: removed

- name: install Elasticsearch
  become: yes
  yum:
    name: "{{ es_rpm_url }}"
    state: installed

- name: Copy jvm.options File
  become: yes
  template: src=jvm.options.j2 dest=/etc/elasticsearch/jvm.options owner=elasticsearch group=elasticsearch mode=0644 force=yes
  notify: restart elasticsearch

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0666
  notify: restart elasticsearch

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
